### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by jeyldii** [citilinkru/camunda-client-go#13]
http://camunda-process/engine-rest/external-task/fetchAndLock: net/http: request canceled (Client.Timeout exceeded while awaiting headers), sleeping: 26 seconds","time":"2019-12-20T06:59:49Z","title":"camunda-client"}

Как это решить?

**Comment by liderman** [comment]
Hi,
I added support for go modules, this solves the problem.
[Here](https://github.com/citilinkru/camunda-client-go/tree/master/examples) are instructions and code examples that should help.
