### ISSUE TITLE
Invalid QueryFetchAndLockTopic.TenantIdIn type 

### ISSUE THREAD

**Issue by bosskurt** [citilinkru/camunda-client-go#29]
There is a problem with the type of "QueryFetchAndLockTopic.TenantIdIn". I get an error with type *string but It works If I change it to *[]string.

Current: `QueryFetchAndLockTopic.TenantIdIn *string json:"tenantIdIn,omitempty"`

```
TenantIdIn := "test"
proc.AddHandler(
            &[]camundaclientgo.QueryFetchAndLockTopic{
                  {TopicName: "testTopic", TenantIdIn: &TenantIdIn},
      },
```
error:

{"level":"debug","error":"failed pull: request error: response error with status code 400: Cannot construct instance of java.lang.String[]: no String-argument constructor/factory method to deserialize from String value ('test')\n
at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 193] (through reference chain: org.camunda.bpm.engine.rest.dto.externaltask.FetchExternalTasksExtendedDto["topic
s"]->java.util.ArrayList[1]->org.camunda.bpm.engine.rest.dto.externaltask.FetchExternalTasksDto$FetchExternalTaskTopicDto["tenantIdIn"]), sleeping: 2 seconds","time":"2021-11-17T12:02:25Z","message":"Camunda"}

Suggested: `QueryFetchAndLockTopic.TenantIdIn *[]string json:"tenantIdIn,omitempty"`

```
proc.AddHandler(
	&[]camundaclientgo.QueryFetchAndLockTopic{
		{TopicName: "testTopic", TenantIdIn: &[]string{"test"}},
	},
```

**Comment by liderman** [comment]
Hi,
Fixed in #30 (release v2.3.2).
Example of use:
```go
proc.AddHandler(
	&[]camundaclientgo.QueryFetchAndLockTopic{
		{TopicName: "testTopic", TenantIdIn: []string{"test"}},
	},
```
