### ISSUE TITLE
What is the official status of v2?

### ISSUE THREAD

**Issue by mlaflamm** [citilinkru/camunda-client-go#36]
I am wondering if v2 is a recommended version or is it experimental? Against which version should someone submit a new PR? 

At the time I am writing this, the most recent commit in master (5b9b9ff) removed all reference to v2. This is confusing to know that there is a v2 out there but there is no mention of it in the README when landing on the main github page of the project. 

Thank you.

**Comment by liderman** [comment]
In commit 5b9b9ff, the "/v2" suffix was removed. it was used before the introduction of go modules.
All releases are listed here: https://github.com/citilinkru/camunda-client-go/releases
Current version is 3.0.0

**Comment by mlaflamm** [comment]
You are right, the version does not need to be in every go file. On the other hand, the `/v3` suffix needs to be added in the first line of the `go.mod` file. 

```
module github.com/citilinkru/camunda-client-go/v3
```

Right now `go get` fetch the version v1.1.2 by default and v3 is not reachable. 

```
$ go get github.com/citilinkru/camunda-client-go@latest
go: added github.com/citilinkru/camunda-client-go v1.1.2

$ go get github.com/citilinkru/camunda-client-go/v3
go: module github.com/citilinkru/camunda-client-go@upgrade found (v1.1.2), but does not contain package github.com/citilinkru/camunda-client-go/v3
```

**Comment by liderman** [comment]
@mlaflamm 
Thank you for noticing.
Fixed!

v1:
```bash
go list -m -versions github.com/citilinkru/camunda-client-go 
github.com/citilinkru/camunda-client-go v0.1.0 v0.1.1 v1.0.0 v1.1.0 v1.1.1 v1.1.2
```
v2:
```bash
go list -m -versions github.com/citilinkru/camunda-client-go/v2
github.com/citilinkru/camunda-client-go/v2 v2.0.0 v2.0.1 v2.1.0 v2.1.1 v2.2.0 v2.3.0 v2.3.1 v2.3.2 v2.3.3
```
v3:
```bash
go list -m -versions github.com/citilinkru/camunda-client-go/v3
github.com/citilinkru/camunda-client-go/v3 v3.0.1
```

Example install latest version:
```bash
go get github.com/citilinkru/camunda-client-go/v3
```
or
```bash
go get github.com/citilinkru/camunda-client-go/v3@v3.0.1
```

Example install previous version:
```bash
go get github.com/citilinkru/camunda-client-go/v2
```
or
```bash
go get github.com/citilinkru/camunda-client-go/v2@v2.3.3
```
