### ISSUE TITLE
startPuller

### ISSUE THREAD

**Issue by vlkalashnikov** [citilinkru/camunda-client-go#45]
```
func (p *Processor) startPuller(query camundaclientgo.QueryFetchAndLock, handler Handler) {
	var tasksChan = make(chan *camundaclientgo.ResLockedExternalTask)

	maxParallelTaskPerHandler := p.options.MaxParallelTaskPerHandler
	if maxParallelTaskPerHandler < 1 {
		maxParallelTaskPerHandler = 1
	}

	// create worker pool
	for i := 0; i < maxParallelTaskPerHandler; i++ {
		p.workerGroup.Add(1)
		go p.runWorker(handler, tasksChan)
	}

	go func() {
		retries := 0
		for {
			select {
			case <-p.ctx.Done():
				close(tasksChan)
				return
			default:
				tasks, err := p.client.ExternalTask.FetchAndLock(query)
				if err != nil {
					if retries < 60 {
						retries += 1
					}
					p.logger(fmt.Errorf("failed pull: %w, sleeping: %d seconds", err, retries))
					time.Sleep(time.Duration(retries) * time.Second)
					continue
				}
				retries = 0

				for _, task := range tasks {
					tasksChan <- task
				}
			}
		}
	}()
}
```
В рутине в бесконечном цикле нет возможности проставить паузу между запросами. С увеличением кол-ва экстернал тасков - увеличивается сетевой трафик и забивается пул конекций

**Comment by liderman** [comment]
@vlkalashnikov похоже это не является проблемой реализации API-клиента. Это похоже на проблему производительности сервера Camunda.

Метод API FetchAndLock реализует паттерн "Long Polling", который позволяет не сбрасывать соединение (не отвечать на запрос) до тех пор пока:
а) сервер будет готов вернуть задание для выполнения
б) с момента запроса прошло время большее чем задано в `asyncResponseTimeout`

т.е. сервер не сразу закрывает соединение, если у него ещё нет нового задания, а пытается ждать определённое время. Именно по этому задержка между успешными ответами тут не допустима, т.к. это противоречит самому паттерну "Long Polling", который стремится доставлять данные без задержек.

В случае же ошибки запроса пауза нужна и она тут есть, и даже с динамически растущей задержкой.

Так что логично, что чем больше обработчиков вы добавили, тем больше постоянных соединений к серверу Camunda будет одновременно существовать. Количество одновременных соединений = количеству обработчиков добавленных через `AddHandler`.

Но важно понимать, что количество топиков НЕ равно количеству соединений, т.к. один обработчик может обрабатывать сразу несколько топиков.

Если ваша задача действительно предполагает большое количество обработчиков, то рекомендую сразу перейти к тюнигу конфигурации Camunda. В ином случае пробуйте занизить `asyncResponseTimeout` или оптимизировать обработчики, чтобы они подписывались сразу на несколько топиков.
