### ISSUE TITLE
when modify processinstance, the datatype is wrong on ReqModifyProcessInstance.Instructions.Variables

### ISSUE THREAD

**Issue by gerdong** [citilinkru/camunda-client-go#47]
When I call the Modify method of ProcessInstance, a parameter of type ReqModifyProcessInstance is required, which contains an slice of type ReqModifyProcessInstanceInstruction struct, and its "Variables" property should be an object of type map[string]ReqProcessVariable, not a slice of type ReqProcessVariable. 
The official documentation description is: A JSON object containing variable key-value pairs. Each key is a variable name and each value a JSON variable value object.
```go
type ReqModifyProcessInstanceInstruction struct {
	// ...
	// A JSON object containing variable key-value pairs.
	// Each key is a variable name and each value a JSON variable value object.
	Variables []ReqProcessVariable `json:"variables"`
}
```

**Comment by liderman** [comment]
@gerdong Thanks for your bug report.
Fixed in version v3.4.1
